export const _enum = {
  AGUARDANDO_PAGAMENTO: 0,
  AGUARDANDO_CONFIRMAÇÃO: 1,
  SENDO_PREPARADO: 2,
  AGUARDANDO_ENTREGADOR: 3,
  SENDO_ENTREGUE: 4,
  AGUARDANDO_COLETA: 5,
  COMPLETO: 6,
  CANCELADO_PELO_CLIENTE: 7,
  CANCELADO_PELO_RESTAURANT: 8
}
